/**
 * Status / error messages and the report footer.
 */

import { t } from "./lang.ts";

// ---------------------------------------------------------------------------
// Status & error messages (used in index.ts, rollup.ts)
// ---------------------------------------------------------------------------

export const MSG = {
  noActivity: t("过去24小时无活动。", "No activity in the last 24 hours."),
  summaryFailed: t("⚠️ 摘要生成失败。", "⚠️ Summary generation failed."),
  skillsFailed: t("⚠️ Skills 摘要生成失败。", "⚠️ Skills summary generation failed."),
  trendingNoData: t(
    "⚠️ 今日趋势数据获取失败，无法生成报告。",
    "⚠️ Trending data unavailable, unable to generate report.",
  ),
  trendingFailed: t("⚠️ 趋势报告生成失败。", "⚠️ Trending report generation failed."),
} as const;

// ---------------------------------------------------------------------------
// Footer (used in report.ts)
// ---------------------------------------------------------------------------

export const FOOTER = {
  autoGen: t("本日报由", "This digest is auto-generated by"),
} as const;
