/**
 * Status / error messages and the report footer.
 */

import { t } from "./lang.ts";

// ---------------------------------------------------------------------------
// Status & error messages (used in index.ts, rollup.ts)
// ---------------------------------------------------------------------------

export const MSG = {
  noActivity: t("Không có hoạt động trong 24 giờ qua.", "No activity in the last 24 hours."),
  summaryFailed: t("⚠️ Tạo tóm tắt thất bại.", "⚠️ Summary generation failed."),
  skillsFailed: t("⚠️ Tạo tóm tắt Skills thất bại.", "⚠️ Skills summary generation failed."),
  trendingNoData: t(
    "⚠️ Không lấy được dữ liệu xu hướng hôm nay, không thể tạo báo cáo.",
    "⚠️ Trending data unavailable, unable to generate report.",
  ),
  trendingNothingNew: t(
    "Không có kho nào mới hoặc biến động đáng kể so với các báo cáo trước.",
    "No repositories are new or have moved significantly since earlier reports.",
  ),
  trendingFailed: t("⚠️ Tạo báo cáo xu hướng thất bại.", "⚠️ Trending report generation failed."),
} as const;

// ---------------------------------------------------------------------------
// Footer (used in report.ts)
// ---------------------------------------------------------------------------

export const FOOTER = {
  autoGen: t("Bản tin hàng ngày này được tạo tự động bởi", "This digest is auto-generated by"),
} as const;
